#!/usr/bin/env bash
# konzolno-radio - за слушане на български радиостанции онлайн в GNU/Linux.

###############
# История
#########
# 1.0.9 версия
# автор: Ivaylo Kuzev
#
# Обновени URL адреси за Radio MaxxFM, Radio Belisimo, Radio City .
# Добавяне на Volume информация .
# Премахване на ICY info от информацията .
# Премахване на Радио Веселина, добавяне на Радио Ултра.
# Премахване на MFM Hitradio, добавяне на Radio Mixx .
# Премахване на Dee Jay, добавяне на Радио Vega+ .
# Добавяне на Пример във -s|--stream опцията .
# Премахване на излишната/нежелана информация - (премахване на -i (ignore case) от egrep) .

# 1.0.8 версия
# автор: Ivaylo Kuzev
#
# Ново радио Cyberfolk на мястото на VoodooNet.
# Ново радио Пайнер на мястото на Балканско радио.
# Ново radio tatkovina на мястото на Радио PartyStyle.
# Добавена е опция [-w|--wake] за събуждане.
# Добавяне на хоризонтална линия, за отделяне на някои елементи.
# Ново hiphop радио Radio 5 polk на мястото на YAKATA RABOTA .
# Ново hiphop радио Black Sea.
# Актуализиране url адреса на Ghost Rider Radio,
# Добавена е sed във листа на зависимости.

# 1.0.7 версия
# автор: Ivaylo Kuzev
#
# Добавена е проверка за правилно въведено време за запис от -r|--record опция.
# Добавена е проверка за валиден URL адрес при опция -s|--stream
# Добавена е по добра проверка за липсващи зависимости.
# Премахнато е пренасянето на следващ ред, за по четлив помощен текст от -h|--help опция.
#
# 1.0.6 версия
# автор: Ivaylo Kuzev
#
# Заместване на #!/bin/bash със #!/usr/bin/env bash, което прави програмата по преносима между
# различните UNIX-подобни операционни системи.
# Оправени са адресите на някои стрийминги - Радио 1 рок, Veronika, Energy, Балканско радио
# Вече се проверява формата на стрийминг файла ,и тогава се решава дали да стартира плейъра със опция (-playlist) или не.
# Добавени са 4 нови радиостанции - PowerFM, Радио КуКу, Твоето Радио, Радио 1
# ----------------------------------------------------------------------------
#
# 1.0.5 версия
# автор: Ivaylo Kuzev
#
# Добавени са две нови радиостанции Радио Варна, Радио Хоризонт
# Добавени са дълги опции --play|--list|--genre|--record|--stream
# Променен е пътя където по подразбиране се инсталира програмата (/usr/bin) .
# Оправена е грешка във опцията -u|--update
# ----------------------------------------------------------------------------
#
# 1.0.4 версия
# автор: Ivaylo Kuzev
#
# Добавена е опция -u|--update която проверява за налична нова версия, и по желание я инсталира
# Вече пускането на радиостанция от stream url се извършва от (-s опцията)
# Премахната е опцията -v
# Добавени са команди mute/pause/stop/voldown/volup за ремоте мениджмънт през fifo
# Вече -h|--help се показват във стил man страница
# Оправени са на некои грешки относно изписването на некои радиостанции
# Вече радиото не спира, ако интернета умре за секунда/две - (автоматично се рестартира)
# Добавено е инфо за основни клавиши (когато изберете некое радио)
# ----------------------------------------------------------------------------
#
# 1.0.3 версия
# автор: Ivaylo Kuzev
#
# Оправяне на некои правописни грешки във кода
# Добавяне на проверка дали е инсталиран mplayer
# ----------------------------------------------------------------------------
#
# 1.0.2 версия
# автор: Ivaylo Kuzev
#
# Нов по приятен интерфейс, добавени са нови цветове, също листа на всички радиа (-l опцията)
# вече се показва на три колонки.
# Добавен съпорт показване на заглавието на песента която звучи (стига радиото да го поддържа)
# Оправен е линка на радио City
# Добавени са нови 10 радиостанции - повечето хип хоп, също нов жанр CHR
# ----------------------------------------------------------------------------
#
# 1.0.1.dev версия
# автор: Ivaylo Kuzev
#
# Добавени нови опции -r -u -v
# Актуализирани и добавяне нови радиостанции
# Добавяне на цветен изход плюс други черешки по скрипта
# Добавен изход на български език
# ----------------------------------------------------------------------------
#
# 1.0.0 версия
#
# Първоначална версия (шаблон)
# URL адрес: https://gist.github.com/abozhilov/1230188
# автор: Asen Bozhilov
#
# ----------------------------------------------------------------------------
# The MIT License (MIT)
# Copyright (c) 2011 Asen Bozhilov
# Copyright (c) 2014-2015 Ivaylo Kuzev
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Изчисти екрана
clear

# Името на програмата
# изглежда по-приятно, отколкото $0, който съдържа пълния път.
PROG="${0##*/}"

# Текущата версия
VERSION="1.0.9"

# Заглавен ред - показва се най отгоре, когато е стартирана програмата
BANNER="${PROG} ${VERSION}"

# Цветен текст
red=$'\e[0;31m'
green=$'\e[0;32m'
ylw=$'\e[0;33m'
blue=$'\e[0;34m'
pur=$'\e[0;35m'
cyn=$'\e[0;36m'
end=$'\e[0m'
greenb=$'\e[1;32m'

# Провери за следните зависимости
DEPENDS=( 'bash' 'curl' 'cat' 'mplayer' 'egrep' 'pr' 'sed' 'less' )

for dep in "${DEPENDS[@]}"
do
    if ! type -p ${dep} >/dev/null
    then
        printf "%s\n" "${red}Командата - ${dep} не може да бъде намерена.. Моля инсталирайте ${dep} и стартирайте $PROG отново. Изход${end}" >&2
        exit 1
    fi
done

# Проверка за инсталиран 'sound-theme-freedesktop'
if [ ! -f "/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga" ]; then
  printf "%s\n" "${red}Файла - alarm-clock-elapsed.oga не е намерен.. Моля инсталирайте sound-theme-freedesktop и стартирайте $PROG отново. Изход${end}" >&2
  exit 1
fi

# Обнови версията (ако има налична такава)
LAST_VERSION="$(curl -silent https://github.com/ivoarch/konzolno-radio/releases/latest | \
        grep -i location: | sed 's/^.*\/tag\/\([^\/]*\)\r$/\1/')"
URI="https://github.com/ivoarch/konzolno-radio/archive/${LAST_VERSION}.tar.gz"

update(){
    if [[ $VERSION != $LAST_VERSION ]]; then
        printf "%s\n" "${green}[Добри новини] Налична е нова версия - $LAST_VERSION${end}"
        printf "%s\n" "${blue}Искали да актуализирате? (y/n):${end} "
        read answer
        if [[ $answer == "y" ]];then
            pushd "$(mktemp -d "/tmp/tmp.XXXXXXXXXX")"
            curl -O -L "$URI"
            tar -xvf "$LAST_VERSION".tar.gz
            cd konzolno-radio-"$LAST_VERSION"
            make install || return 1
            popd
            # по добро решение?
            sed -i "s/${VERSION}/${LAST_VERSION}/g" /usr/bin/"$PROG"
            printf "%s\n" "${green}Поздравления! Вашата версия беше актуализирана на $LAST_VERSION${end}"
        else
            exit 1
        fi
    else
        printf "%s\n" "${green}Поздравления! Имате инсталирана последната версия $VERSION${end}"
    fi
}

# Изкарва помощтен текст
print_help() {
    cat | less -S << 'EOD'
konzolno-radio(1)            User Manuals                konzolno-radio(1)

NAME
     konzolno-radio - конзолно радио

SYNOPSIS
     konzolno-radio [ Опция] [Номер на радио]

DESCRIPTION
     konzolno-radio - е шел скрипт, конзолно интернет радио, което има за цел да бъде бързо,
     и лесно за използване, като по този начин да улесни слушането на български радиостанции
     онлайн в Gnu/Linux (с помощта на Mplayer).

OPTIONS
     [-l | --list]    Показва списък на всички радиостанции.
     [-p | --play]    Пусни радиостанция от списъка.
     [-g | --genre]   Покажи списък на наличните жанрове. (Комбинирайте със опция -l)
     [-s | --stream]  Въведете URL адреса за стрийминг радиостанцията, която желаете.
     [-r | --record]  Запишете mp3 радио стрийминг на файл.
     [-h | --help]    Показва този помощен текст.
     [-u | --update]  Проверява за нова версия, и ако има такава я инсталира. (трябва да сте root за да инсталирате)
     [-w | --wake]    Аларма

EXAMPLES
     Пусни радио станция:
     konzolno-radio -l -- показва списък на всички радиостанции
     konzolno-radio -p 6 -- пуска шеста радиостанция от списъка (Радио Maxx FM)
     konzolno-radio -r 6 -- записва .mp3 файл на шестата радиостанция от списъка (Радио Maxx FM)

     Пусни радио станция от спецефичен жанр:
     konzolno-radio -g -l -- показва всички жанрове
     konzolno-radio -g 2 -l -- показва всички радиостанции от жанр (Денс)
     konzolno-radio -g 2 -p 0 -- пуска първата радиостанция от жанр (Денс) - (Радио Maxx FM)
     konzolno-radio -g 2 -r 0 -- записва .mp3 файл на първата радиостанция от жанр (Денс) - (Радио Maxx FM)

COMMANDS
     mute       Изключване на звука
     pause      Паузиране на радиото (при повторно натискане продължава възпроизвеждането)
     stop       Спиране на радиостанцията и излизане от програмата
     voldown    Намаляване силата на звука
     volup      Увеличаване силата на звука

KEYBOARD CONTROL
        m
             Изключване на звука
        p / SPACE
             Паузиране на радиото (при повторно натискане продължава възпроизвеждането)
        q / ESC
             Спиране на радиостанцията и излизане от програмата
        9 и 0
             Увеличаване/намаляване силата на звука

AUTHOR
     Ivaylo Kuzev <ivkuzev [at] gmail [dot] com>

REPORTING BUGS
     Доклад за грешки на https://github.com/ivoarch/konzolno-radio/issues

SEE ALSO
     mplayer(1)

Linux                            Apr 04, 2015                           konzolno-radio(1)

EOD
     exit 0
}

# Създай фифо файл за ремоте контрол
FIFO="/tmp/mplayer.fifo"
if [[ ! -p $FIFO ]]; then
    rm $FIFO 2>/dev/null
    mkfifo $FIFO
fi

# Имена на радиостанции
NAMES=(
    "БГрадио"
    "Радио 1 рок"
    "Z-Rock"
    "Energy"
    "Радио City"
    "Радио Fresh"
    "Maxx FM"
    "Радио N-Joy"
    "BTV Радио"
    "Melody"
    "Радио FM+"
    "Алфа радио"
    "Радио Nova"
    "Стар ФМ"
    "Фокус"
    "Джаз ФМ"
    "Зорана"
    "Радио Тангра"
    "Traffic радио"
    "I Hate Mondays"
    "Радио Екстра"
    "Радио vis-vitalis"
    "Vibes радио"
    "Eilo - progressive"
    "Eilo - house"
    "Радио Belisimo"
    "24x7 Rock радио"
    "Ghost Rider Radio"
    "Радио Вероника"
    "Радио Ултра"
    "Радио Пайнер"
    "Радио Фолк Бг"
    "Дарик радио"
    "Дарик носталджи"
    "Radio Tatkovina"
    "KatraFM"
    "Радио Мая"
    "Radio Mixx"
    "CyberFolk"
    "Radio 5 polk"
    "Radio Vega+"
    "Hot Dance"
    "Радио Viva Bg"
    "Радио Реакция"
    "Радио Варна"
    "Радио Хоризонт"
    "Радио 1"
    "PowerFM"
    "Радио КуКу"
    "Твоето радио"
    "Radio Black Sea"
)

# Стрийминги
STREAMS=(
    "http://149.13.0.80/bgradio128.m3u"
    "http://149.13.0.81/radio1rock.ogg"
    "http://ng.btv.bg/m3u/zrock.m3u"
    "http://149.13.0.80/nrj.ogg"
    "http://149.13.0.80/city.ogg"
    "http://193.108.24.21:8000/fresh.m3u"
    "http://141.0.169.245/maxx.m3u"
    "http://ng.btv.bg/m3u/njoy.m3u"
    "http://ng.btv.bg/m3u/btvradio.m3u"
    "http://ng.btv.bg/m3u/melody.m3u"
    "http://www.slusham.com/radio/fmplus.m3u"
    "http://188.126.1.25:8000/AlphaRadio.m3u"
    "http://149.13.0.81/nova.ogg"
    "http://pulsar.atlantis.bg:8000/starfm.m3u"
    "http://online.focus-radio.net:8100/sofia.m3u"
    "http://ng.btv.bg/m3u/jazzfm.m3u"
    "http://streaming.gesbg.com/zorana.pls"
    "http://stream-02.radiotangra.com:8000/Tangra-high.m3u"
    "http://radio.networx-bg.com:8002/listen.pls"
    "http://77.70.53.35:8000/listen.pls"
    "http://play.radioextra.org/extra.m3u"
    "http://online.vvitalis.com/vis-vitalis.m3u"
    "http://195.24.54.14:8000/listen.pls"
    "http://eilo.org:8000/progressive.m3u"
    "http://eilo.org:8000/house.m3u"
    "http://radiobelisimo.ovo.bg/listen.pls"
    "http://193.107.70.107:8000/stream.ogg.m3u"
    "http://79.98.108.176:8022/listen.pls"
    "http://149.13.0.80/veronika.ogg"
    "http://www.ultranet.biz/ultrapernik.m3u"
    "http://87.120.6.86:8000/hq.m3u"
    "http://folkbg.net/folkbg.net.m3u"
    "http://slusham.com/radio/darik.m3u"
    "http://dariknostalgie.bg/wp-content/uploads/nostalgie.m3u"
    "http://67.205.111.204:8000/bg.m3u"
    "http://www.katrafm.com/katrafm_mp3pro.m3u"
    "http://mail.rntel.com:9000/listen.pls"
    "http://83.97.65.98:9000/listen.pls"
    "http://play.radiocyberfolk.com/cyberfolk.m3u"
    "http://79.98.108.171:8006/listen.pls"
    "http://www.ultranet.biz/vegablagoevgrad.m3u"
    "http://listen.hotget.net:8000/radio.m3u"
    "http://stream.radioextra-bg.net:8000/viva-eurodance.m3u"
    "http://reakcia.net/stream/stream.m3u"
    "http://broadcast.masters.bg:8000/live.m3u"
    "http://stream.bnr.bg:8002/horizont.mp3.m3u"
    "http://149.13.0.80/radio1.ogg"
    "http://a1.virtualradio.eu:8000/powerfm.mp3.m3u"
    "http://stereo.wavestreamer.com:1774/listen.pls?sid=1"
    "http://79.98.108.173:8010/radio.m3u"
    "http://174.36.232.226:8012/stream.m3u"
)

# Жанрове
GENRES=(
    "Българска музика"
    "ХипХоп и R&B"
    "Денс"
    "Поп"
    "Рок и Хеви метъл"
    "Ретро"
    "Разни"
    "Хаус"
    "Новини"
    "Прогресив"
    "Поп Фолк"
    "CHR"
)

BGMUSIC=(0 16 34 38)
BLACK=(39 50)
DANCE=(6 20 25 37 41)
POP=(3 4 7 8 9 10 12 21 35 37 46 49)
ROCK=(1 2 13 17 19 21 26 27 43)
RETRO=(9 20 25 33 41)
VARIOUS=(5 15 19 35 42 44 45 48)
HOUSE=(6 11 18 24)
NEWS=(8 14 32)
PROGRESSIVE=(22 23)
POP_FOLK=(28 29 30 31 40)
CHR=(4 36 37 47 49)

# получава жанра
getGenre() {
    if [[ "$1" -eq "0" ]]; then
        genre=("${BGMUSIC[@]}")
    elif [[ "$1" -eq "1" ]]; then
        genre=("${BLACK[@]}")
    elif [[ "$1" -eq "2" ]]; then
        genre=("${DANCE[@]}")
    elif [[ "$1" -eq "3" ]]; then
        genre=("${POP[@]}")
    elif [[ "$1" -eq "4" ]]; then
        genre=("${ROCK[@]}")
    elif [[ "$1" -eq "5" ]]; then
        genre=("${RETRO[@]}")
    elif [[ "$1" -eq "6" ]]; then
        genre=("${VARIOUS[@]}")
    elif [[ "$1" -eq "7" ]]; then
        genre=("${HOUSE[@]}")
    elif [[ "$1" -eq "8" ]]; then
        genre=("${NEWS[@]}")
    elif [[ "$1" -eq "9" ]]; then
        genre=("${PROGRESSIVE[@]}")
    elif [[ "$1" -eq "10" ]]; then
       genre=("${POP_FOLK[@]}")
    elif [[ "$1" -eq "11" ]]; then
       genre=("${CHR[@]}")
    else
        printf "%s\n" "${red}Няма такъв жанр${end}"
    fi
}

# Стрийминг формати
FILE_FORMATS=".flac|.wma|.mms|.wmv|.ogg|.avi|.aac|.mov|.flv|.mpg|.mpeg|.asf|rtsp://|mms://|.rm"
PLAYLIST_FORMATS=".pls|.asx|.m3u"

# Плейър
# Проверява за формата и тогава решава дали ще стартира с -playlist опция или не.
if echo ${STREAMS[$2]} | egrep -i "(${PLAYLIST_FORMATS})" > /dev/null 2>&1 ; then
PLAY_COMMAND="mplayer \
-idle -input file=$FIFO -quiet -nolirc -cache 500 -cache-min 1 -loop 0 -prefer-ipv4 -noframedrop -playlist"
elif echo ${STREAMS[$2]} | egrep -i "(${FILE_FORMATS})" > /dev/null 2>&1 ; then
PLAY_COMMAND="mplayer \
-idle -input file=$FIFO -quiet -nolirc -cache 500 -cache-min 1 -loop 0 -prefer-ipv4 -noframedrop"
fi

# Записвач
DEFAULT_FILE="StreamDump"
FILETYPE="mp3"
POSTFIX="$(date +%y-%m-%d_%H:%M)"
# Проверява за формата и тогава решава дали ще стартира с -playlist опция или не.
if echo ${STREAMS[$2]} | egrep "(${PLAYLIST_FORMATS})" > /dev/null 2>&1 ; then
RECORDER="mplayer \
-nolirc -dumpstream -dumpfile ${DEFAULT_FILE}_${POSTFIX}.${FILETYPE} -noframedrop -playlist"
elif echo ${STREAMS[$2]} | egrep -i "(${FILE_FORMATS})" > /dev/null 2>&1 ; then
RECORDER="mplayer \
-nolirc -dumpstream -dumpfile ${DEFAULT_FILE}_${POSTFIX}.${FILETYPE} -noframedrop"
fi

# Аларма
ALARMCLOCK="mplayer -really-quiet -nolirc -loop 0"

# Проверява аргументите
if [ -z "$1" -o "$1" == "-h" -o "$1" == "--help" ]; then
    print_help
# Ремоте контрол
elif [[ "$1" == "mute" ]]; then
    echo "mute" > $FIFO
elif [[ "$1" == "pause" ]]; then
    echo "pause" > $FIFO
elif [[ "$1" == "stop" ]]; then
    echo "quit" > $FIFO
elif [[ "$1" == "voldown" ]]; then
    echo "volume -20" > $FIFO
elif [[ "$1" == "volup" ]]; then
    echo "volume +20" > $FIFO
# Информация за налична нова версия
elif [[ "$1" == "--update" ]] || [[ "$1" == "-u" ]]; then
    update
# Въведете url на радиостанция
elif [[ "$1" == "--stream" ]] || [[ "$1" == "-s" ]]; then
    printf "%s\n" "${greenb}$BANNER${end}"
    printf "%s\n" "${blue}Пример:${end} http://url-radio-streaming"
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
    printf %s "${blue}Въведете URL адреса за стрийминг радиостанцията:${end} "
    read URL
    regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
    if [[ $URL =~ $regex ]]; then  # провери за url адрес
        printf "%s\n" "${blue}Натиснете ${ylw}'q'${end}${blue} за да излезете${end}"
        printf "%s\n" "${blue}Регулирайте силата на звука със vol- ${ylw}'9'${end}${blue} и vol+ ${end}${ylw}'0'${end}"
        printf "%s\n" "${blue}За да паузирате ${end}${ylw}'p'${end}${blue} за изключване на звука ${end}${ylw}'m'${end}"
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        $PLAY_COMMAND "${URL}" 2>&1 | GREP_COLOR='0;33' egrep --color=always "(Name|Genre|Website|Bitrate|Starting playback...|Volume)"
    else
        printf "%s\n" "${red}Грешка... адреса $URL е навалиден!${end}"
        printf "%s\n" "${red}Въведете правилно адреса за стрийминг радиостанцията.${end}"
        exit 1
    fi
# Списък на радиостанции
elif [[ "$1" == "--list" ]] || [[ "$1" == "-l" ]]; then
    printf "%s\n" "${greenb}$BANNER${end}"
    printf "%s\n" "${blue}>>>  ${pur}Списък на всички радиостанции${end}${blue}  <<<${end}"
    i=0
    while [[ "$i" -lt "${#NAMES[*]}" ]]; do
        echo $i "♪" ${NAMES[$i]} | sed -e "s/[^[:blank:]]\{1,\}/$ylw&$end/1" \
            -e "s/[^[:blank:]]\{1,\}/$pur&$end/2" \
            -e "s/[^[:blank:]]\{1,\}/$cyn&$end/3" \
            -e "s/[^[:blank:]]\{1,\}/$cyn&$end/4" \
            -e "s/[^[:blank:]]\{1,\}/$cyn&$end/5" \
            -e "s/[^[:blank:]]\{1,\}/$cyn&$end/6"
        ((i++))
    done |  pr -3 -l 24 -t -T -J
# Пусни радио от списъка
elif [[ "$1" == "--play" ]] || [[ "$1" == "-p" ]]; then
    if [[ -n "${STREAMS[$2]}" ]]; then
        printf "%s\n" "${greenb}$BANNER${end}"
        printf "%s\n" "${blue}Натиснете ${ylw}'q'${end}${blue} за да излезете${end}"
        printf "%s\n" "${blue}Регулирайте силата на звука със vol- ${ylw}'9'${end}${blue} и vol+ ${end}${ylw}'0'${end}"
        printf "%s\n" "${blue}За да паузирате ${end}${ylw}'p'${end}${blue} за изключване на звука ${end}${ylw}'m'${end}"
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        $PLAY_COMMAND ${STREAMS[$2]} 2>&1 | GREP_COLOR='0;33' egrep --color=always "(Name|Genre|Website|Bitrate|Starting playback...|Volume)"
        exit $?
    else
        printf "%s\n" "${red}Моля, вижте списъка на наличните радиостанции.${end}"
        exit 1
    fi
# Записва радиостанция от списъка
elif [[ "$1" == "--record" ]] || [[ "$1" == "-r" ]]; then
    if [[ -n "${STREAMS[$2]}" ]]; then
        printf "%s\n" "${greenb}$BANNER${end}"
        printf "%s\n" "${ylw}(s)${blue} за секунди, ${ylw}(m)${blue} за минути, ${ylw}(h)${blue} за часове.${end}"
        printf "%s\n" "${blue}Пример: ${ylw}20s${blue} за 20 секунди, ${ylw}20m${blue} за 20 минути, ${ylw}2h${blue} за 2 часа.${end}"
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        printf %s "${blue}Въведете желаното време за запис:${end} "
        read LENGTH
        if [[ "$LENGTH" = [0-9]*[smh] ]]; then
        $RECORDER ${STREAMS[$2]} >/dev/null 2>&1 &
        PID="$!"
        sleep "${LENGTH}"
        kill "${PID}"
        exit $?
        else
            printf "%s\n" "${red}${LENGTH} е грешно! Моля въведете правилно желаното време за запис!${end}"
            exit 1
        fi
    else
        printf "%s\n" "${red}Моля, вижте списъка на наличните радиостанции.${end}"
        exit 2
    fi
elif [[ "$1" == "--wake" ]] || [[ "$1" == "-w" ]]; then
        printf "%s\n" "${greenb}$BANNER${end}"
        printf "%s\n" "${blue}Пример: ${ylw}20s${blue} за 20 секунди, ${ylw}20m${blue} за 20 минути, ${ylw}2h${blue} за 2 часа.${end}"
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        printf %s "${blue}Въведете след колко време да алармира:?${end} "
        read waits
        if [[ "$waits" = [0-9]*[smh] ]]; then
          printf "%s\n" "${pur}Натиснете ${ylw}'Control + C'${pur} за да спрете алармата.${end}"
          sleep "$waits" && $ALARMCLOCK "/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga"
        else
          printf "%s\n" "${red}${waits} е грешно! Моля въведете правилно желаното време до алармата!${end}"
          exit 1
        fi
        printf "%s\n" "${green}Изход!${end}"
# Жанрове
elif [[ "$1" == "--genre" ]] || [[ "$1" == "-g" ]]; then
    # Списък на жанрове
    if [[ "$2" == "--list" ]] || [[ "$2" == "-l" ]]; then
        printf "%s\n" "${greenb}$BANNER${end}"
        printf "%s\n" "${blue}>>>  ${pur}Списък на всички жанрове${end}${blue}  <<<${end}"
        i=0
        while [[ "$i" -lt "${#GENRES[*]}" ]]; do
            echo $i "♪" ${GENRES[$i]} | sed -e "s/[^[:blank:]]\{1,\}/$ylw&$end/1" \
                -e "s/[^[:blank:]]\{1,\}/$pur&$end/2" \
                -e "s/[^[:blank:]]\{1,\}/$cyn&$end/3" \
                -e "s/[^[:blank:]]\{1,\}/$cyn&$end/4" \
                -e "s/[^[:blank:]]\{1,\}/$cyn&$end/5" \
                -e "s/[^[:blank:]]\{1,\}/$cyn&$end/6"
           ((i++))
        done
    elif [[ $2 =~ ^[0-9]+$ ]]; then
        if [ "$2" -ge "0" -a "$2" -lt "${#GENRES[*]}" ]; then
            getGenre "$2"
            if [ -z "$3" -o "$3" == "--list" ] || [ -z "$3" -o "$3" == "-l" ]; then
                printf "%s\n" "${greenb}$BANNER${end}"
                printf "%s\n" "${blue}>>>  ${pur}${GENRES[$2]}${end}${blue}  <<<${end}"
                i=0
                while [[ "$i" -lt "${#genre[*]}" ]]; do
                    echo $i "♪" ${NAMES[${genre[$i]}]} | sed -e "s/[^[:blank:]]\{1,\}/$ylw&$end/1" \
                        -e "s/[^[:blank:]]\{1,\}/$pur&$end/2" \
                        -e "s/[^[:blank:]]\{1,\}/$cyn&$end/3" \
                        -e "s/[^[:blank:]]\{1,\}/$cyn&$end/4" \
                        -e "s/[^[:blank:]]\{1,\}/$cyn&$end/5" \
                        -e "s/[^[:blank:]]\{1,\}/$cyn&$end/6"
                    ((i++))
                done
            # запиши от жанр
            elif [[ "$3" == "--record" ]] || [[ "$3" == "-r" ]]; then
                if [[ -n "${genre[$4]}" ]]; then
                    printf "%s\n" "${greenb}$BANNER${end}"
                    printf "%s\n" "${ylw}(s)${blue} за секунди, ${ylw}(m)${blue} за минути, ${ylw}(h)${blue} за часове.${end}"
                    printf "%s\n" "${blue}Пример: ${ylw}20s${blue} за 20 секунди, ${ylw}20m${blue} за 20 минути, ${ylw}2h${blue} за 2 часа.${end}"
                    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
                    printf %s "${blue}Въведете желаното време за запис:${end} "
                    read LENGTH
                    if [[ "$LENGTH" = [0-9]*[smh] ]]; then
                    $RECORDER ${STREAMS[${genre[$4]}]} >/dev/null 2>&1 &
                    PID="$!"
                    sleep "${LENGTH}"
                    kill "${PID}"
                    exit $?
                    else
                    printf "%s\n" "${red}${LENGTH} е грешно! Моля въведете правилно желаното време за запис!${end}"
                    exit 1
                    fi
                else
                    printf "%s\n" "${red}Моля, вижте списъка на наличните радиостанции от този жанр.${end}"
                    exit 2
                fi
            # пусни от жанр
            elif [[ "$3" == "--play" ]] || [[ "$3" == "-p" ]]; then
                if [[ -n "${genre[$4]}" ]]; then
                    printf "%s\n" "${greenb}$BANNER${end}"
                    printf "%s\n" "${blue}Натиснете ${ylw}'q'${end}${blue} за да излезете${end}"
                    printf "%s\n" "${blue}Регулирайте силата на звука със vol- ${ylw}'9'${end}${blue} и vol+ ${end}${ylw}'0'${end}"
                    printf "%s\n" "${blue}За да паузирате ${end}${ylw}'p'${end}${blue} за изключване на звука ${end}${ylw}'m'${end}"
                    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
                    $PLAY_COMMAND ${STREAMS[${genre[$4]}]} 2>&1 | GREP_COLOR='0;33' egrep --color=always "(Name|Genre|Website|Bitrate|Starting playback...|Volume)"
                    exit $?
                else
                    printf "%s\n" "${red}Моля, вижте списъка на наличните радиостанции от този жанр.${end}"
                    exit 1
                fi
            else
                printf "%s\n" "${red}Няма такава опция: Използвайте ${PROG} -h за помощ.${end}"
                exit 2
            fi
        else
            printf "%s\n" "${red}Моля, вижте списъка от жанрове.${end}"
            exit 1
        fi
    else
        printf "%s\n" "${red}Няма такава опция: Използвайте ${PROG} -h за помощ.${end}"
        exit 2
    fi
else
    printf "%s\n" "${red}Няма такава опция: Използвайте ${PROG} -h за помощ.${end}"
    exit 2
fi
exit 0

#####
# Край на скрипта
################ ####  ##    #
